// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JustinaSystem.Entities;

internal partial class Appointment
{
    [Key]
    public int appointment_id { get; set; }

    public int customer_id { get; set; }

    public int dog_id { get; set; }

    public int groomer_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime check_in_time { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime checkout_in_time { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime length { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string notes { get; set; }

    [ForeignKey("customer_id")]
    [InverseProperty("Appointments")]
    public virtual Customer customer { get; set; }

    [ForeignKey("dog_id")]
    [InverseProperty("Appointments")]
    public virtual Dog dog { get; set; }

    [ForeignKey("groomer_id")]
    [InverseProperty("Appointments")]
    public virtual Groomer groomer { get; set; }

    [ForeignKey("appointment_id")]
    [InverseProperty("appointments")]
    public virtual ICollection<Service> services { get; set; } = new List<Service>();
}