// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JustinaSystem.Entities;

internal partial class Dog
{
    [Key]
    public int dog_id { get; set; }

    public int customer_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string dog_name { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string breed { get; set; }

    [Column(TypeName = "date")]
    public DateTime? date_of_birth { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string sex { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string vet { get; set; }

    public double? weight { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string color { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string ok_with_other_dogs { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string has_allergies { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string on_medication { get; set; }

    [StringLength(3)]
    [Unicode(false)]
    public string take_apik { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string notes { get; set; }

    [InverseProperty("dog")]
    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    [ForeignKey("customer_id")]
    [InverseProperty("Dogs")]
    public virtual Customer customer { get; set; }

    [InverseProperty("dog")]
    public virtual ICollection<vaccination> vaccinations { get; set; } = new List<vaccination>();
}