// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JustinaSystem.Entities;

internal partial class Groomer
{
    [Key]
    public int groomer_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string first_name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string last_name { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string phone_number { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string email_address { get; set; }

    [Column(TypeName = "date")]
    public DateTime? enrollment_date { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string notes { get; set; }

    [InverseProperty("groomer")]
    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();
}