// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JustinaSystem.Entities;

internal partial class Payment
{
    [Key]
    public int payment_id { get; set; }

    public int? service_id { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime date_time { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string method_of_payment { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal payment_amount { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal gst { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string notes { get; set; }

    [ForeignKey("service_id")]
    [InverseProperty("Payments")]
    public virtual Service service { get; set; }
}