// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JustinaSystem.Entities;

internal partial class Service
{
    [Key]
    public int service_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string service_name { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string description { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? price { get; set; }

    [InverseProperty("service")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [ForeignKey("service_id")]
    [InverseProperty("services")]
    public virtual ICollection<Appointment> appointments { get; set; } = new List<Appointment>();
}