// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace JustinaSystem.Entities;

internal partial class vaccination
{
    [Key]
    public int vaccine_id { get; set; }

    public int? dog_id { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string vaccine_name { get; set; }

    [Column(TypeName = "date")]
    public DateTime? start_date { get; set; }

    [Column(TypeName = "date")]
    public DateTime? end_date { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string notes { get; set; }

    [ForeignKey("dog_id")]
    [InverseProperty("vaccinations")]
    public virtual Dog dog { get; set; }
}